services:
  adguardhome:
    container_name: 'adguardhome'
    image: 'adguard/adguardhome:v0.107.52'
    restart: unless-stopped
    ports:
      - '8082:80'
      - '8442:443'
      - '53:53'
      - '53:53/udp'
    volumes:
      - ./data/config:/opt/adguardhome/conf
      - ./data/data:/opt/adguardhome/work/data
      - ./data/letsencrypt:/opt/adguardhome/letsencrypt
    networks:
      - adguardhome_network

networks:
  adguardhome_network:
    name: 'adguardhome_network'
    ipam:
      config:
        - subnet: 172.18.7.0/24
