services:
  vmagent:
    container_name: 'vmagent'
    image: 'victoriametrics/vmagent:v1.101.0'
    restart: unless-stopped
    volumes:
      - ./data:/vmagentdata
      - ./config/:/etc/prometheus
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--remoteWrite.url=https://${VM_ENDPOINT:?error}/api/v1/write'
    networks:
      - monitoring_network
  node-exporter:
    container_name: 'node-exporter'
    image: 'prom/node-exporter:v1.8.0'
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring_network
  cadvisor:
    container_name: 'cadvisor'
    image: 'gcr.io/cadvisor/cadvisor:v0.49.1'
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
    - monitoring_network
  endlessh:
    container_name: 'endlessh'
    image: 'shizunge/endlessh-go:latest'
    restart: unless-stopped
    ports:
      - '2222:2222'
    command: '-interval_ms 10000 -geoip_supplier ip-api -enable_prometheus -logtostderr -v=1'
    networks:
      - monitoring_network

networks:
  monitoring_network:
    name: 'monitoring_network'
    external: true
#    ipam:
#      config:
#        - subnet: 172.18.6.0/24
