services:
  vmagent:
    container_name: 'vmagent'
    image: 'victoriametrics/vmagent:v1.101.0'
    restart: unless-stopped
    ports:
      - 8429:8429
    volumes:
      - ./data:/vmagentdata
      - ./config/:/etc/prometheus
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=https://${VM_ENDPOINT:?error}/api/v1/write"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    name: 'monitoring_network'
    external: true
#    ipam:
#      config:
#        - subnet: 172.18.6.0/24
