services:
  uptime-kuma:
    container_name: 'uptime-kuma'
    image: 'louislam/uptime-kuma:1.23.13-alpine'
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - uptime_network

networks:
  uptime_network:
    name: 'uptime_network'
    ipam:
      config:
        - subnet: 172.18.4.0/24
