services:
  wg-easy:
    container_name: 'wg-easy'
    image: 'ghcr.io/wg-easy/wg-easy:14'
    restart: unless-stopped
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    volumes:
      - ./data/config:/etc/wireguard
      - ./data/lib-modules:/lib/modules
    environment:
      PASSWORD_HASH: ${PASSWORD_HASH:?error}
      WG_HOST: ${WG_HOST:?error}
      WG_PERSISTENT_KEEPALIVE: '25'
      WG_ALLOWED_IPS: ${WG_ALLOWED_IPS:-0.0.0.0/0}
      UI_TRAFFIC_STATS: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wg_network

networks:
  wg_network:
    name: 'wg_network'
    ipam:
      config:
        - subnet: 172.18.1.0/24
