services:
  npm:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    ports:
      - '443:443'
      - '81:81'
    environment:
      DISABLE_IPV6: true
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - npm_network

networks:
  npm_network:
    name: 'npm_network'
    ipam:
      config:
        - subnet: 172.18.0.0/24
