services:
  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce:2.21.0-rc2-alpine'
    restart: unless-stopped
    ports:
      - '2080:9000'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_network

networks:
  portainer_network:
    name: 'portainer_network'
    ipam:
      config:
        - subnet: 172.18.2.0/24
