services:
  portainer-agent:
    container_name: 'portainer_agent'
    image: 'portainer/agent:2.21.0-rc2-alpine'
    restart: unless-stopped
    ports:
      - '9001:9001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_network

networks:
  portainer_network:
    name: 'portainer_network'
    ipam:
      config:
        - subnet: 172.18.2.0/24
