services:
  vaultwarden:
    container_name: 'vaultwarden'
    image: 'vaultwarden/server:1.34.3-alpine'
    restart: unless-stopped
    ports:
      - '3080:80'
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      DOMAIN: ${DOMAIN:?error}
      ADMIN_TOKEN: ${ADMIN_TOKEN:?error}
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID:?error}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY:?error}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED:-true}
      LOG_FILE: '/data/vaultwarden.log'
      EXTENDED_LOGGING: true
      YUBICO_CLIENT_ID: ${YUBICO_CLIENT_ID:?error}
      YUBICO_SECRET_KEY: ${YUBICO_SECRET_KEY:?error}
    volumes:
      - ./data/vaultwarden:/data
    networks:
      - vaultwarden_network
    logging:
      driver: local
      options:
        max-size: "200m"

  backup:
    container_name: 'vaultwarden-backup'
    image: 'ttionya/vaultwarden-backup:1.25.1'
    restart: unless-stopped
    volumes:
      - ./data/vaultwarden:/bitwarden/data
      - ./data/vault-backup:/config
    environment:
      RCLONE_REMOTE_NAME: 'VaultwardenBackup'
      RCLONE_REMOTE_DIR: '/vaultwarden_backup/'
      CRON: '0 0 * * *'
      ZIP_ENABLE: 'TRUE'
      ZIP_PASSWORD: ${BACKUP_ZIP_PASSWORD:?error}
      ZIP_TYPE: '7z'
      BACKUP_KEEP_DAYS: 7
      PING_URL: ${BACKUP_PING_URL:?error}
      TIMEZONE: 'Asia/Ho_Chi_Minh'
    networks:
      - vaultwarden_network
    logging:
      driver: local
      options:
        max-size: "200m"

networks:
  vaultwarden_network:
    name: 'vaultwarden_network'
    ipam:
      config:
        - subnet: 172.18.3.0/24
